version: '3.8'

services:
  certbot-renew:
    build:
      context: .
      dockerfile: Dockerfile.renew
    environment:
      - DOMAIN=${DOMAIN}    
    volumes:
      - "./certs:/output-certs"
      - "./backups:/backups"
      - "./letsencrypt:/etc/letsencrypt"
    network_mode: "host"
    command: renew --cert-name "$DOMAIN" --standalone

  certbot-obtain:
    build:
      context: .
      dockerfile: Dockerfile.obtain
    environment:
      - DOMAIN=${DOMAIN}
    volumes:
      - "./certs:/output-certs"
      - "./letsencrypt:/etc/letsencrypt"
    network_mode: "host"
    command: certonly -d "$DOMAIN" --standalone --register-unsafely-without-email --agree-tos
